### ISSUE TITLE
Specifications

### ISSUE THREAD

**Issue by voiceofthedead** [Marfusios/bitfinex-client-websocket#11]
If you specified a bit more details on NewOrderRequest, I think a lot of people would appreciate it very much.
Also you wrote "Price (Not required for market orders)" there, but you didn't make constructor, that doesn't need to receive price as one of parameters, not counting empty constructor. Which leaves me to either use empty one, which is quite amusing, or write 0 in price section ?

**Comment by Marfusios** [comment]
Hello,

this library is meant to be a just lightweight/raw layer over Bitfinex API. 
So it is expected that user/developer is familiar with official websockets documentation, which can be found here: 
[https://docs.bitfinex.com/v2](https://docs.bitfinex.com/v2/reference#ws-auth-new-order)
