### ISSUE TITLE
Reconnection issues.. how to fix?

### ISSUE THREAD

**Issue by ColossusFX** [Marfusios/bitfinex-client-websocket#17]
Please could you leave an example of how you are re-subscribing after disconnect.
Thanks

**Comment by Marfusios** [comment]
Hello, 

could you provide a full log? How exactly it doesn't work? 
My bots work 24/7 without issue. 
Are you using the latest version of the library? Are you correctly resubscribing to channels after reconnection (see #12)?

**Comment by ColossusFX** [comment]
Thanks for the reply.

I must have missed the other closed issue.

Could you give more detail about how you re-sub to to channels?

Thanks for the hard work doing this and BitMEX library.

**Comment by Marfusios** [comment]
See #12, there is a code snippet or latest sample [Project.cs](https://github.com/Marfusios/bitfinex-client-websocket/blob/master/test_integration/Bitfinex.Client.Websocket.Sample/Program.cs)
