### ISSUE TITLE
Install via NuGet: Target Framework 2.0 Error

### ISSUE THREAD

**Issue by NEA8** [Marfusios/bitfinex-client-websocket#33]
Hello,

I have the following error when trying to install via NuGet:

-------------------------------------------------------------------------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Bitfinex.Client.Websocket 3.0.91'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
-------------------------------------------------------------------------------------------------
Even though I have choose the .NET 2.0 Version (see screenshot):

![grafik](https://user-images.githubusercontent.com/52570606/60722185-6ac43180-9f30-11e9-8e80-f0ff94a705f7.png)

Im a newbie what I' doing wrong?

**Comment by Marfusios** [comment]
Hello @NEA8 

.NET Framework 2.0 is really really old, like 2002 year. 
The library targets .NET Standard 2.0 which is API subset for all targets (.NET Framework, .NET Core, Mono, etc). Here is a compatibility table: 
![image](https://user-images.githubusercontent.com/3494837/60794679-93d00680-a16a-11e9-882d-86da54a19aac.png)
[link](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

So you need to target .NET Framework 4.6.1 (Windows only) or .NET Core 2.0 (multiplatform, Windows, Linux, MacOS).

**Comment by NEA8** [comment]
Dear Marfusios,

I'm sorry for the late answer. I was on hollyday. It works now.
I have configured my projekt to the ".Net Framework 4.6.1" but I have the same error. My mistake was that I did not activate the checkbox for the project I wanted. Newie mistakes :).

NEA8
