### ISSUE TITLE
Open / Start the projekt.

### ISSUE THREAD

**Issue by NEA8** [Marfusios/bitfinex-client-websocket#34]
Hello,

I have a problem when I try to open the Projekt with the Visual Studio Express 2017:
![grafik](https://user-images.githubusercontent.com/52570606/61947170-cf5d3400-afa4-11e9-98fb-cb36300b5d32.png)

The following message appears:
![grafik](https://user-images.githubusercontent.com/52570606/61947227-fae01e80-afa4-11e9-8473-f592b8f26a46.png)
I confirm the message with "OK".

After that I have the following structure in "Solution Explorer":
![grafik](https://user-images.githubusercontent.com/52570606/61947715-42b37580-afa6-11e9-849d-136762c65fa8.png)
I see that are many file are missing??

And the following Warnings:
![grafik](https://user-images.githubusercontent.com/52570606/61947751-58289f80-afa6-11e9-9ea5-b6942b1a96de.png)

There's nothing I can do now. No NuGet installation, no .cs files and so on. Can someone help?

NEA8

**Comment by Marfusios** [comment]
Hello, 

that's really weird. Do you have [.NET Core SDK](https://dotnet.microsoft.com/download) installed? 
Try run `dotnet --version` in the console. 

Also, I'm using [VS 2019](https://visualstudio.microsoft.com/vs/), maybe try that newest version.

**Comment by NEA8** [comment]
Hello,

thank you very much for the tip. It works now with VS 2019 community.
