### ISSUE TITLE
Expose Symbol property on Ticker and Trade classes

### ISSUE THREAD

**Issue by aquisio** [Marfusios/bitfinex-client-websocket#39]
This is an excellent library. Thank you for creating it.

I have modified my local clone to expose a Symbol property on the Ticker and Trade classes, implemented exactly as you have done in Book and RawBook.

It would be great if this could be added to your codebase, so that I can go back to consuming it from the Nuget package.

Thanks again,
Tim

**Comment by Marfusios** [comment]
Hello @aquisio ,

thanks, please create PR so we can merge it
