### ISSUE TITLE
Order filled not received

### ISSUE THREAD

**Issue by KaiserSozo** [Marfusios/bitfinex-client-websocket#7]
Subscribed to bitfinexAPI.Streams.OrderCreatedStream and bitfinexAPI.Streams.OrderUpdatedStream
After placing order I get into OrderCreatedStream but after order filled I do not get into OrderUpdatedStream. Is it right that I'm waiting info about order filling or any other changes in order after it was accepted by bitfinex in OrderUpdatedStream?

**Comment by Marfusios** [comment]
Hello,

there is a third (fourth) type of the order stream - `OrderCanceledStream` and then you need to check OrderStatus (`Executed` or `Canceled`). A little weird, but it's how their API is defined (sending that info via `order cancel` channel). 

For sake of completeness:
* **OrdersStream** - initial snapshot, all active orders, streamed after successful authentication
* **OrderCreatedStream** - order was created (type: `Active`)
* **OrderUpdatedStream** - order was updated (type: `Active` or `PartiallyFilled`), price/amount was changed
* **OrderCanceledStream** - order was removed (type: `Canceled` or `Executed`)

**Comment by KaiserSozo** [comment]
Thank you!
