### ISSUE TITLE
20051 Stopping. Please try to reconnect

### ISSUE THREAD

**Issue by KaiserSozo** [Marfusios/bitfinex-client-websocket#9]
What should I do when I see message like this: 20051 Stopping. Please try to reconnect
Crete new communicator or all new connection?

**Comment by KaiserSozo** [comment]
Also, I have experienced quotes stopping without that message, that caused in money loss. Is that usual situation? How can I check stream state?

**Comment by KaiserSozo** [comment]
Also, I see that quotes are coming one time in 10 seconds. Why is interval so big? On web site quotes changing severa times in one second.

**Comment by Marfusios** [comment]
Hello,

ticker channel is somehow slow, maybe on purpose... 
Anyway, I don't use it, if I need real-time updates I subscribe to BookStream and TradesStream which are really fast. 

Regarding reconnecting - probably same issue as #12?
